### ISSUE TITLE
fn:available-environment-variables#0 not getting environment vars

### ISSUE THREAD

**Issue by grantmacken** [zadean/xqerl#28]
functions available-environment-variables#0 and fn:environment-variable#1
don't return anything in my docker host
the shell commands, where 'xq' is the running container  name
```
docker exec xq printenv
docker exec xq xqerl eval  'os:getenv().'
```
will both print my env vars,
however  the code fragment below nothing is returned
```
element p { 'vars: [ '  || available-environment-variables()  || ' ]' },
element p { 'var:  [ '  || environment-variable("XQERL_COOKIE")  || ' ]' }
```
I see the test suite covers the functions
`test/QT3-test-suite/fn/environment-variable.xml`
but they don't appear to return what they should.

take care
Grant

**Comment by zadean** [comment]
Hello @grantmacken ,
Due to xqerl being able to be distributed over multiple machines/users, each with their own environment variables, the two functions that deal with environment variables have been quietly disabled.

`fn:available-environment-variables#0` will always return the empty-sequence. This follows the spec:
>See also the note on security under the definition of the fn:environment-variable function. If access to environment variables has been disabled, fn:available-environment-variables always returns the empty sequence.

`fn:environment-variable#1` is similarly blocked and follows the spec:
>Security advice: Queries from untrusted sources should not be permitted unrestricted access to environment variables. For example, the name of the account under which the query is running may be useful information to a would-be intruder. An implementation may therefore choose to restrict access to the environment, or may provide a facility to make fn:environment-variable always return the empty sequence.

**Comment by grantmacken** [comment]
@zadean Thanks, good to to know reasons why.
Perhaps a note on the module reference, would be a good idea.
https://zadean.github.io/xqerl/modules/fn.html#available-environment-variables.

**Comment by zadean** [comment]
I went ahead and implemented the functions but set a config flag to turn them on in #29
